name = "Turtle's Auxiliar Modpack"
author = "Aturtle6813"
version = "mc1.21.4-1.3.0-beta.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1d53f4d7b8eb928e81531b22a4e315e864ba13c5392c61612be52c7f6fcb10bb"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
